---
services:
  db:
    image: docker.io/postgres:17
    restart: unless-stopped
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=db
    volumes:
      - db:/var/lib/postgresql/data/

  app:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PGHOST=db
      - PGDATABASE=db
      - PGUSER=db
      - PGPASSWORD=db
    depends_on:
      - db
    develop:
      watch:
        - action: rebuild
          path: src/
        - action: sync+restart
          path: html/
          target: /html

volumes:
  db:
